module.exports = {
  siteUrl: 'https://chinesenamegenerator.online',
  generateRobotsTxt: true,
  changefreq: 'weekly',
  priority: 0.7,
  sitemapSize: 7000,
  exclude: ['/api/*'],
  additionalPaths: async (config) => [
    { loc: '/', changefreq: 'weekly', priority: 1.0 },
    { loc: '/chinesenamegenerator', changefreq: 'weekly', priority: 0.9 },
    { loc: '/blog', changefreq: 'weekly', priority: 0.8 },
    { loc: '/blog/chinese-name-pronunciation', changefreq: 'monthly', priority: 0.7 },
    { loc: '/blog/chinese-names-for-boys', changefreq: 'monthly', priority: 0.7 },
    { loc: '/blog/chinese-names-for-girls', changefreq: 'monthly', priority: 0.7 },
    { loc: '/features', changefreq: 'monthly', priority: 0.7 },
    { loc: '/how-it-works', changefreq: 'monthly', priority: 0.7 },
    { loc: '/testimonials', changefreq: 'monthly', priority: 0.7 },
    { loc: '/faq', changefreq: 'monthly', priority: 0.7 },
    { loc: '/pricing', changefreq: 'monthly', priority: 0.7 },
    { loc: '/legal/privacy-policy', changefreq: 'yearly', priority: 0.5 },
    { loc: '/legal/terms-of-service', changefreq: 'yearly', priority: 0.5 },
    { loc: '/legal/cookie-policy', changefreq: 'yearly', priority: 0.5 },
    { loc: '/legal/gdpr', changefreq: 'yearly', priority: 0.5 },
  ],
}; 