# Wrangler configuration for Cloudflare Pages
name = "chinese-name-maker"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-04-26"

[site]
bucket = ".next"
entry-point = "_worker"

[build]
command = "npm run build"
watch_dir = "src"
pages_build_output_dir = ".next"

[build.upload]
format = "service-worker" 