import { Metadata } from 'next';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Brain, Zap, Target, Shield, Globe, Clock, CheckCircle, ArrowRight } from 'lucide-react';

export const metadata: Metadata = {
  title: 'AI Smart Chinese Name Generator | Advanced AI Technology',
  description: 'Experience our AI-powered Chinese name generator with advanced algorithms. Create personalized, culturally authentic Chinese names using artificial intelligence technology.',
  keywords: 'AI chinese name generator, smart name generator, AI naming technology, artificial intelligence names, personalized chinese names',
};

const aiFeatures = [
  {
    icon: <Brain className="h-8 w-8" />,
    title: 'Advanced AI Algorithms',
    description: 'Our AI analyzes thousands of classical Chinese texts, modern naming patterns, and cultural contexts to generate authentic names.',
    benefit: 'More accurate and culturally appropriate names'
  },
  {
    icon: <Target className="h-8 w-8" />,
    title: 'Personalized Matching',
    description: 'Input your preferences, personality traits, and background. Our AI creates names that perfectly match your unique characteristics.',
    benefit: 'Names tailored specifically for you'
  },
  {
    icon: <Globe className="h-8 w-8" />,
    title: 'Cultural Intelligence',
    description: 'AI understands deep cultural meanings, historical contexts, and modern naming trends across different Chinese regions.',
    benefit: 'Culturally authentic and respectful names'
  },
  {
    icon: <Clock className="h-8 w-8" />,
    title: 'Instant Generation',
    description: 'Get multiple high-quality name suggestions within seconds. No waiting, no delays, just immediate results.',
    benefit: 'Fast and efficient naming process'
  },
];

const comparisonFeatures = [
  { feature: 'Generation Speed', traditional: 'Manual Research (Hours)', ai: 'Instant (Seconds)', advantage: true },
  { feature: 'Cultural Accuracy', traditional: 'Limited Knowledge', ai: 'Comprehensive Database', advantage: true },
  { feature: 'Personalization', traditional: 'Generic Suggestions', ai: 'Tailored to You', advantage: true },
  { feature: 'Name Variations', traditional: '1-3 Options', ai: 'Multiple Options', advantage: true },
  { feature: 'Meaning Depth', traditional: 'Basic Meanings', ai: 'Deep Cultural Context', advantage: true },
  { feature: 'Learning Ability', traditional: 'Static', ai: 'Continuously Improving', advantage: true },
];

const howItWorks = [
  {
    step: 1,
    title: 'Input Your Information',
    description: 'Share your name, preferences, birth date, and personality traits with our AI system.',
    icon: '📝'
  },
  {
    step: 2,
    title: 'AI Analysis',
    description: 'Our advanced algorithms analyze your input against our vast database of Chinese names and meanings.',
    icon: '🧠'
  },
  {
    step: 3,
    title: 'Smart Generation',
    description: 'AI generates personalized Chinese names that match your characteristics and cultural preferences.',
    icon: '✨'
  },
  {
    step: 4,
    title: 'Receive Your Names',
    description: 'Get multiple beautiful Chinese names with detailed meanings, pronunciations, and cultural context.',
    icon: '🎯'
  },
];

export default function AINameGenerator({ params }: { params: { lang: string } }) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-blue-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
      <div className="container mx-auto px-4 py-8">
        {/* Hero Section */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 px-4 py-2 rounded-full text-sm font-medium mb-6">
            <Brain className="h-4 w-4" />
            AI Smart Technology
          </div>
          <h1 className="text-4xl md:text-6xl font-bold text-gray-900 dark:text-white mb-6">
            AI Smart Chinese Name Generator
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto mb-8">
            Experience the future of Chinese naming with our advanced AI technology. Get personalized, culturally authentic Chinese names generated by artificial intelligence that understands deep cultural meanings and modern preferences.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link href={`/${params.lang}`}>
              <Button className="bg-purple-600 hover:bg-purple-700 text-white px-8 py-4 text-lg">
                <Brain className="mr-2 h-5 w-5" />
                Try AI Smart Generator
              </Button>
            </Link>
            <Link href={`/${params.lang}/free-chinese-names`}>
              <Button variant="outline" className="px-8 py-4 text-lg">
                Browse Free Names
              </Button>
            </Link>
          </div>
        </div>

        {/* AI Features Section */}
        <div className="mb-16">
          <h2 className="text-3xl font-bold text-center text-gray-900 dark:text-white mb-12">
            Why Choose AI Smart Technology?
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {aiFeatures.map((feature, index) => (
              <Card key={index} className="text-center hover:shadow-xl transition-all duration-300">
                <CardHeader>
                  <div className="flex justify-center text-purple-600 dark:text-purple-400 mb-4">
                    {feature.icon}
                  </div>
                  <CardTitle className="text-xl mb-2">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-gray-600 dark:text-gray-300 mb-4">
                    {feature.description}
                  </CardDescription>
                  <div className="bg-purple-50 dark:bg-purple-900/20 p-3 rounded-lg">
                    <p className="text-sm font-medium text-purple-700 dark:text-purple-300">
                      {feature.benefit}
                    </p>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* How It Works Section */}
        <div className="mb-16">
          <h2 className="text-3xl font-bold text-center text-gray-900 dark:text-white mb-12">
            How AI Smart Generator Works
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {howItWorks.map((step, index) => (
              <div key={index} className="text-center">
                <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-lg hover:shadow-xl transition-shadow">
                  <div className="text-4xl mb-4">{step.icon}</div>
                  <div className="w-8 h-8 bg-purple-600 text-white rounded-full flex items-center justify-center text-sm font-bold mx-auto mb-4">
                    {step.step}
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">
                    {step.title}
                  </h3>
                  <p className="text-gray-600 dark:text-gray-300">
                    {step.description}
                  </p>
                </div>
                {index < howItWorks.length - 1 && (
                  <div className="hidden lg:block absolute top-1/2 right-0 transform translate-x-1/2 -translate-y-1/2">
                    <ArrowRight className="h-6 w-6 text-purple-400" />
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Comparison Section */}
        <div className="mb-16">
          <h2 className="text-3xl font-bold text-center text-gray-900 dark:text-white mb-12">
            AI vs Traditional Methods
          </h2>
          <div className="bg-white dark:bg-gray-800 rounded-2xl p-8 shadow-lg overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-gray-200 dark:border-gray-700">
                    <th className="text-left py-4 px-6 font-semibold text-gray-900 dark:text-white">Feature</th>
                    <th className="text-center py-4 px-6 font-semibold text-gray-500 dark:text-gray-400">Traditional Methods</th>
                    <th className="text-center py-4 px-6 font-semibold text-purple-600 dark:text-purple-400">AI Smart Technology</th>
                  </tr>
                </thead>
                <tbody>
                  {comparisonFeatures.map((item, index) => (
                    <tr key={index} className="border-b border-gray-100 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/50">
                      <td className="py-4 px-6 font-medium text-gray-900 dark:text-white">{item.feature}</td>
                      <td className="py-4 px-6 text-center text-gray-500 dark:text-gray-400">{item.traditional}</td>
                      <td className="py-4 px-6 text-center">
                        <div className="flex items-center justify-center gap-2">
                          <CheckCircle className="h-5 w-5 text-green-500" />
                          <span className="text-purple-600 dark:text-purple-400 font-medium">{item.ai}</span>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* CTA Section */}
        <div className="text-center bg-gradient-to-r from-purple-600 to-blue-600 rounded-2xl p-12 text-white">
          <h2 className="text-3xl font-bold mb-4">
            Ready to Experience AI Smart Naming?
          </h2>
          <p className="text-xl opacity-90 mb-8 max-w-2xl mx-auto">
            Join thousands of users who have discovered their perfect Chinese names using our advanced AI technology. Get started for free today!
          </p>
          <Link href={`/${params.lang}`}>
            <Button className="bg-white text-purple-600 hover:bg-gray-100 px-8 py-4 text-lg font-semibold">
              <Brain className="mr-2 h-5 w-5" />
              Generate My AI Chinese Name
            </Button>
          </Link>
        </div>
      </div>
    </div>
  );
} 